### ISSUE TITLE
MGBC-BOM: Conflicting item quantity; mouser-cart vs BOM

### ISSUE THREAD

**Issue by StefanKutschera** [MouseBiteLabs/Game-Boy-Pocket-Color#5]
The Bill of Material (BOM) for the MGBC has different quantities listed compared to the provided mouser-cart[1] https://www.mouser.com/ProjectManager/ProjectDetail.aspx?AccessID=854e7f6cf9

For example: 
Mouser cart: "80-C0603C105K3P" Qty: 100 pieces  <-- vs --> BOM: "C16-19,39,40,48,49,51" Qty: 9 pieces 
Mouser cart: "80-C0603C104M3R"	Qty: 10 pieces <-- vs -->   BOM: "C3, C12, C24, C43, C52, C53": Qty: 6 pieces

"minimum-qty" and "multiple-of-qty" arent containing those quantities. 
While it doesn't seem much, costs be reduced to 2/3 of the current mouser-cart (mouser-cart ~35€ vs BOM ~25€)

Is this something done by design, If so, why?

**Comment by MouseBiteLabs** [comment]
I add extra parts as a preventative measure, but people can change
quantities if they would like. Many people will lose or damage a small
component during installation, and some parts I round up to the next price
break because the cost is nearly negligible or even *cheaper*
(80-C0603C104M3R for example will cost $0.60 for 6 parts, but only $0.25
for 10). And paying $8 shipping for a ten cent part is silly.

I don't know if this is different in Euro. Maybe the price breaks are
different. But by my calculations for USD, putting the exact part amount
required for the project only saves you $4.55 USD.
